# Generated by Django 4.2.17 on 2024-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Valid Phone Number',
                'verbose_name_plural': 'Valid Phone Numbers',
                'ordering': ['-added_at'],
            },
        ),
    ]
